# Ayu Dark Theme
[colors.primary]
background = '#0A0E14'
#foreground = '#B3B1AD'
foreground = '#DFDFDF'

[colors.normal]
black   = '#01060E'
#red     = '#EA6C73'
#red     = '#ca304f'
red     = '#dd435d'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
#cyan    = '#90E1C6'
cyan    = '#6dbda3'
white   = '#C7C7C7'

[colors.bright]
black   = '#686868'
#red     = '#F07178'
#red     = '#d1565f'
red     = '#fb6778'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'
